### ISSUE TITLE
Feature request: Add a macro to specify multiple flags without repeating the type name

### ISSUE THREAD

**Issue by yvt** [MaikKlein/enumflags#12]
While using this crate, I found it rather useful to define a macro like this:

```rust
// public domain
macro_rules! flags {
    ( $($ns:ident::)* {} ) => (
        $($ns::)*empty_bitflag()
    );

    ( $($ns:ident::)* {$tail:ident} ) => (
        $crate::BitFlags::from($($ns::)*$tail)
    );

    // Use `{}` instead of `()` to avoid `unused_parens` warning
    ( $($ns:ident::)* {$head:ident | $($rest:tt)*} ) => ({
        flags![$($ns::)*{$head}] |
        flags![$($ns::)*{$($rest)*}]
    })
}
```

The usage is shown below:

```rust
#[derive(EnumFlags, Copy, Clone, PartialEq, Eq, Hash, Debug)]
#[repr(u8)]
pub enum Test { A = 0b0001, B = 0b0010 }

let flags0 = flags![Test::{}];
let flags1 = flags![Test::{A}];
let flags2 = flags![Test::{A | B}];

assert_eq!(flags0, enumflags::BitFlags::empty());
assert_eq!(flags1, Test::A.into());
assert_eq!(flags2, Test::A | Test::B);
```

Perhaps could you consider including this macro in `enumflags`?

**Comment by MaikKlein** [comment]
Hm I don't think it adds much besides the fact that a single variant doesn't have to specify `.into()` considering that you can also import the variants into scope with `use Test::*`. 

But maybe it is already worth it for the `.into` alone. I have to think about it for a bit.

**Comment by NieDzejkob** [comment]
Note that `use Test::*;` can pollute your namespace, which makes it a PITA if your variant names are generic because you're actually using namespaces.

**Comment by yvt** [comment]
Closing this as I meanwhile published a standalone crate that implements this idea: <https://github.com/yvt/flags-macro-rs>
