### ISSUE TITLE
Support Zero (0) value for discriminant 

### ISSUE THREAD

**Issue by MightyE** [MaikKlein/enumflags#19]
I'm trying to represent ICMP Type field as an enum using EnumFlags.  Type `0` is "[Echo Reply](https://en.wikipedia.org/wiki/Internet_Control_Message_Protocol#Control_messages)".

If I try to represent this, however, it throws [this compile time exception](https://github.com/MaikKlein/enumflags/blob/master/enumflags_derive/src/lib.rs#L90) 
```error: proc-macro derive panicked
 --> src/layer4/icmp.rs:6:10
  |
6 | #[derive(EnumFlags, Copy, Clone, Debug)]
  |          ^^^^^^^^^
  |
  = help: message: Null flag is not allowed
```

From this code:
```rust
#[derive(EnumFlags, Copy, Clone, Debug)]
#[repr(u8)]
pub enum IcmpType {
    EchoReply = 0,
    DestinationUnreachable = 3,
    SourceQuench = 4,
...
```

I'm trying to understand this logic, and whether it's strictly necessary.  And what is the work-around when you're representing constants outside of your control (i.e. I can't just start at a value of 1 because if you cast back to the u8 value it will be incorrect)?

**Comment by NieDzejkob** [comment]
You are completely misunderstanding the purpose of this crate. It's for making bit flags, not setting an enum's value. [There is no need for external crates for the latter.](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=feadabf31ad9f83a7e2d3cff8ffa71d0)

**Comment by MightyE** [comment]
I see, you're right, I misunderstood the purpose.
